<a href="https://colab.research.google.com/github/Rohitsingh24-cloud/pytorch/blob/main/dataloaderanddatasetinpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
from sklearn.datasets import make_classification

In [3]:
#step 1 creatae a synthetic classification dataset  using sklearn

In [4]:
x,y=make_classification(n_samples=10,n_features=2,n_informative=2,n_redundant=0,random_state=2,n_classes=2)
#     n_smaple  -       number of smaple/row
#     n_features        number of column
#     n_informative     number of important_feature
#     n_redundant       number of redundant features
#     n_classes         number of classes in output
#     random_state      for reproducibility


In [5]:
x

array([[ 1.19233761,  1.68984837],
       [ 2.10468347,  0.08822   ],
       [ 1.04115518, -1.91602762],
       [ 0.28432141, -0.11450983],
       [-0.67458929, -0.89813178],
       [ 0.97869965, -0.57896825],
       [-1.30136943,  0.79786149],
       [ 1.17062352,  0.99746752],
       [-0.12196157, -2.58441629],
       [-0.98692549,  0.68339532]])

In [6]:
y

array([1, 1, 0, 0, 0, 1, 0, 1, 1, 0])

In [7]:
#convert the data to pytorch tensors


In [8]:
x=torch.tensor(x,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [9]:
from torch.utils.data import Dataset,DataLoader

In [10]:
class customdataset(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels
  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self,idx):
    x=self.features[idx]
    y=self.labels[idx]
    return x,y

In [11]:
dataset=customdataset(x,y)

In [12]:
len(dataset)

10

In [13]:
dataset[0]

(tensor([1.1923, 1.6898]), tensor(1))

In [14]:
dataset[2]

(tensor([ 1.0412, -1.9160]), tensor(0))

In [15]:
#dataloader

In [16]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [17]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 0.9787, -0.5790],
        [-0.9869,  0.6834]])
tensor([1, 0])
--------------------------------------------------
tensor([[1.1706, 0.9975],
        [1.1923, 1.6898]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.1220, -2.5844],
        [-1.3014,  0.7979]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 2.1047,  0.0882],
        [ 0.2843, -0.1145]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.0412, -1.9160],
        [-0.6746, -0.8981]])
tensor([0, 0])
--------------------------------------------------


In [18]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [19]:
class customdataset(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels
  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self,idx):
    x=self.features[idx]
    y=self.labels[idx]
    return x,y


In [20]:
train_dataset=customdataset(X_train_tensor,y_train_tensor)
test_dataset=customdataset(X_test_tensor,y_test_tensor)

In [23]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

In [24]:
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out





learning_rate = 0.1
epochs = 25

In [26]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])
model=model.double()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
#model.parameter is an iterator that give all paramter in  model
loss_function=nn.BCELoss()
# define loop
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features.double())

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1).double())
    #zero gradient
    optimizer.zero_grad()
    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()


    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5083670986043002
Epoch: 1, Loss: 0.4025758217352909
Epoch: 1, Loss: 0.367023016527958
Epoch: 1, Loss: 0.3397748352875424
Epoch: 1, Loss: 0.33540904481516254
Epoch: 1, Loss: 0.23283203239237812
Epoch: 1, Loss: 0.24669888131660622
Epoch: 1, Loss: 0.22552700835886036
Epoch: 1, Loss: 0.22746870107421063
Epoch: 1, Loss: 0.19837761244956875
Epoch: 1, Loss: 0.2681420329183567
Epoch: 1, Loss: 0.1900911814811191
Epoch: 1, Loss: 0.25708678504032345
Epoch: 1, Loss: 0.28416891373070075
Epoch: 1, Loss: 0.14393463828868117
Epoch: 2, Loss: 0.2108588849303022
Epoch: 2, Loss: 0.19649618600290136
Epoch: 2, Loss: 0.22329596995612544
Epoch: 2, Loss: 0.1658183956696598
Epoch: 2, Loss: 0.14997900186167626
Epoch: 2, Loss: 0.16001461270043654
Epoch: 2, Loss: 0.20712978313459865
Epoch: 2, Loss: 0.11790728533982514
Epoch: 2, Loss: 0.1286749409933179
Epoch: 2, Loss: 0.13095865576285529
Epoch: 2, Loss: 0.23585344371495753
Epoch: 2, Loss: 0.12614204942952628
Epoch: 2, Loss: 0.13709795829861302
Ep

In [27]:
# model evaluation
with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model.forward(batch_features.double())
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == batch_labels).float().mean()
    print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.53125
Accuracy: 0.7109375
Accuracy: 0.6640625
Accuracy: 0.5555555820465088
