<a href="https://colab.research.google.com/github/Rohitsingh24-cloud/pytorch/blob/main/operation%20on%20tensor%20in%20pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print("gpu is available")
else:
  print("gpu is not available")

gpu is available


creating a tensor

In [4]:
#using empty i.e create an empty tensor


In [6]:
a=torch.empty(2,3)

In [7]:
a

tensor([[-6.9206e-24,  4.3589e-41,  2.0077e-20],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00]])

In [8]:
type(a)

torch.Tensor

In [9]:
#using zeros we create tensor of zeros

In [14]:
b=torch.zeros(2,3)

In [15]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
#using ones to create tensor of one

In [17]:
c=torch.ones(2,3)

In [18]:
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
#using rand to generate tensor of random number value btween 0-1

In [20]:
d=torch.rand(2,3)

In [21]:
d

tensor([[0.3684, 0.8378, 0.5742],
        [0.9915, 0.6723, 0.9577]])

In [22]:
#using seed . so that value should be random but each time we run we get same random value

In [26]:
torch.manual_seed(100)
e=torch.rand(2,3)
e

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [27]:
#custom tensor

In [29]:
f=torch.tensor([[1,2,23],[4,5,6]])
f

tensor([[ 1,  2, 23],
        [ 4,  5,  6]])

In [30]:
#using arange

In [31]:
g=torch.arange(0,5)
g

tensor([0, 1, 2, 3, 4])

In [33]:
#using linspace
h=torch.linspace(1,5,2)
h

tensor([1., 5.])

In [34]:
#using eye

In [35]:
i=torch.eye(5)
i

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [36]:
#using full it create a tensor of given size for that number

In [37]:
j=torch.full((2,2),3)
j

tensor([[3, 3],
        [3, 3]])

tensor shape


In [42]:
x=torch.tensor([[1,2,3],[4,5,5]])
x
x.shape

torch.Size([2, 3])

In [43]:
#if you want to create an empty tensor of same shape

In [44]:
y=torch.empty_like(x)
y

tensor([[       10757832, 133601812905920, 133601812946688],
        [            113, 133601820007648, 133601820007648]])

In [45]:
#for zero

In [46]:
y=torch.zeros_like(x)
y

tensor([[0, 0, 0],
        [0, 0, 0]])

In [47]:
#for one

In [49]:
y=torch.ones_like(y)
x

tensor([[1, 2, 3],
        [4, 5, 5]])

In [61]:
#using random . remember here we have to explicitly define the data type bcs random generate the number between ranges


a=torch.rand_like(x,dtype=torch.float)
a


tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

tensor data type


In [52]:
x.dtype

torch.int64

In [53]:
#specify data type at the tieme of creation of tensor

In [54]:
a=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [55]:
#to convert dtype of one tensor to another type


In [58]:
c=a.to(torch.int)
c
c.dtype

torch.int32

mathematical operation


1)scalar operation


In [62]:
x=torch.rand(2,2)

In [63]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [64]:
#addition

In [65]:
y=x+2
y

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [66]:
#subtraction

In [67]:
y=x-2
y

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [68]:
#multiplication


In [69]:
y=x*2
y

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [70]:
#division


In [71]:
y=x/2
y

tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])

In [72]:
#int division


In [73]:
y=x*100//3
y

tensor([[23., 26.],
        [13., 30.]])

In [74]:
#mod

In [75]:
y=x*100%3
y

tensor([[2.1765, 0.7581],
        [2.8305, 0.1415]])

In [76]:
#power

In [77]:
y=x**2
y

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [78]:
#element wise operation


In [79]:
x=torch.rand(2,3)
y=torch.rand(2,3)

In [80]:
#addition

In [81]:
z=x+y
z

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [82]:
#subtraction

In [83]:
z=x-y
z

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [84]:
#multiplication


In [88]:
z=x*y
z

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [86]:
#division

In [87]:
z=x/y
z

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [89]:
#power

In [90]:
z=x**y
z

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [91]:
#mod


In [92]:
z=x%y
z

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [93]:
#abs


In [94]:
z=abs(y)
z

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])

In [95]:
#negative

In [96]:
z=torch.neg(y)
z

tensor([[-0.5557, -0.9770, -0.4440],
        [-0.9478, -0.7445, -0.4892]])

In [97]:
#round

In [99]:
z=torch.round(x)
z

tensor([[1., 1., 0.],
        [0., 0., 1.]])

In [100]:
#ceil

In [103]:
z=torch.ceil(x)
z

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [102]:
#floor

In [104]:
z=torch.floor(x)
z

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [105]:
#clamp . to put in  a range

In [106]:
z=torch.clamp(x,min=2,max=3)
z

tensor([[2., 2., 2.],
        [2., 2., 2.]])

reduction operation

In [107]:
#sum .sum of all matrix element

In [117]:
a=torch.tensor([[1,2,3],[5,6,7],[8,2,1]],dtype=torch.float64)
a

tensor([[1., 2., 3.],
        [5., 6., 7.],
        [8., 2., 1.]], dtype=torch.float64)

In [109]:
b=torch.sum(a)
b

tensor(35)

In [110]:
#sum along column

In [111]:
b=torch.sum(a,dim=0)
b

tensor([14, 10, 11])

In [112]:
#sum along row

In [113]:
b=torch.sum(a,dim=1)
b

tensor([ 6, 18, 11])

In [114]:
#mean

In [118]:
b=torch.mean(a)
b

tensor(3.8889, dtype=torch.float64)

In [119]:
#mean along column

In [120]:
b=torch.mean(a,dim=0)
b

tensor([4.6667, 3.3333, 3.6667], dtype=torch.float64)

In [121]:
#mean along row

In [122]:
b=torch.mean(a,dim=1)
b

tensor([2.0000, 6.0000, 3.6667], dtype=torch.float64)

In [123]:
#median

In [124]:
b=torch.median(a)
b

tensor(3., dtype=torch.float64)

In [125]:
#median along column

In [126]:
b=torch.median(a,dim=0)
b

torch.return_types.median(
values=tensor([5., 2., 3.], dtype=torch.float64),
indices=tensor([1, 2, 0]))

In [127]:
#maxand min

In [128]:
b=torch.max(a)
c=torch.min(a)
print(b,c)

tensor(8., dtype=torch.float64) tensor(1., dtype=torch.float64)


In [129]:
#product

In [131]:
b=torch.prod(a)
b

tensor(20160., dtype=torch.float64)

In [132]:
#std

In [133]:
b=torch.std(a)
b

tensor(2.6667, dtype=torch.float64)

In [134]:
#variance

In [135]:
b=torch.var(a)
b

tensor(7.1111, dtype=torch.float64)

In [137]:
b=torch.argmax(a)
b

tensor(6)

In [138]:
#argmin . it tell the pos of smallest number

In [139]:
b=torch.argmin(a)
b

tensor(0)

matrix operation

In [148]:
a=torch.randint(size=(2,3),low=0,high=10)
b=torch.randint(size=(3,2),low=0,high=10)
print(a)
print(b)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [149]:
#matrix multiplication

In [150]:
c=torch.matmul(a,b)
c

tensor([[116, 153],
        [166, 225]])

In [151]:
#dot product

In [152]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=torch.dot(a,b)
c

tensor(32)

In [153]:
#transpose

In [156]:
a=torch.randint(size=(2,3),low=0,high=10)

c=torch.transpose(a,0,1)
c

tensor([[2, 7],
        [6, 8],
        [7, 3]])

In [157]:
#determinant

In [160]:
a=torch.randint(size=(2,2),low=0,high=10,dtype=float)
c=torch.det(a)
c

tensor(-12., dtype=torch.float64)

In [161]:
c=torch.inverse(a)
c

tensor([[-0.6667,  0.3333],
        [ 0.2500,  0.0000]], dtype=torch.float64)

comparision operation

In [163]:
#greater than

In [165]:
a=torch.tensor([[2,6,8],[4,5,8]])
b=torch.tensor([[1,2,9],[14,15,6]])


In [167]:
c=a>b
c

tensor([[ True,  True, False],
        [False, False,  True]])

In [168]:
#less than

In [170]:
c=a<b
c

tensor([[False, False,  True],
        [ True,  True, False]])

In [171]:
#equal

In [172]:
c=a==b
c

tensor([[False, False, False],
        [False, False, False]])

In [173]:
#not equal to

In [174]:
c=a!=b
c

tensor([[True, True, True],
        [True, True, True]])

In [175]:
#greater than equal to

In [176]:
c=a>=b
c

tensor([[ True,  True, False],
        [False, False,  True]])

In [177]:
#less than equal to

In [178]:
c=a<=b
c

tensor([[False, False,  True],
        [ True,  True, False]])

In [179]:
#special function

In [180]:
#log

In [189]:
a=torch.tensor([[1,2,3],[4,5,6]],dtype=float)
b=torch.log(a)
b

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]], dtype=torch.float64)

In [182]:
b=torch.exp(a)
b

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [183]:
#sqrt

In [184]:
b=torch.sqrt(a)
b

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])

In [185]:
#sigmoid


In [186]:
b=torch.sigmoid(a)
b

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.9933, 0.9975]])

In [187]:
#softmax

In [190]:
b=torch.softmax(a,dim=0)
b

tensor([[0.0474, 0.0474, 0.0474],
        [0.9526, 0.9526, 0.9526]], dtype=torch.float64)

In [191]:
#relu

In [192]:
b=torch.relu(a)
b

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)