<a href="https://colab.research.google.com/github/Rohitsingh24-cloud/pytorch/blob/main/tensor_operation_on_gpu_in_pytorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

#inplace operation



In [4]:
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[3,4,5],[6,7,8]])



In [5]:
#add in a.    _make it inplace operation

In [6]:
a.add_(b)

tensor([[ 4,  6,  8],
        [10, 12, 14]])

In [7]:
#apply relu and store data to m

In [8]:
a.relu_()

tensor([[ 4,  6,  8],
        [10, 12, 14]])

#copy a tensor


In [9]:
b=a
b

tensor([[ 4,  6,  8],
        [10, 12, 14]])

In [10]:
#but here if a changes b also changes

In [11]:
#so to make it copy separately we use clone

In [13]:
b=torch.clone(a)
b

tensor([[ 4,  6,  8],
        [10, 12, 14]])

In [14]:
id(a)

133834769925328

In [15]:
id(b)

133834769125776

#tensor operation on gpu

In [16]:
import time

In [17]:
device=torch.device('cuda')

In [18]:
#create a new tensor on gpu

In [19]:
a=torch.tensor([[1,2,2],[5,6,5]],device=device)
a

tensor([[1, 2, 2],
        [5, 6, 5]], device='cuda:0')

In [20]:
#moving an existing tensor to gpu

In [22]:
b.to(device)
b

tensor([[ 4,  6,  8],
        [10, 12, 14]])

#reshape tensor

In [26]:
a=torch.tensor([[1,2,3],[4,5,6]])
b=a.reshape((2,1,3))
b

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [27]:
#flatten

In [28]:
b=torch.flatten(a)
b

tensor([1, 2, 3, 4, 5, 6])

In [29]:
#permute . in this we reshape it .i.e we make 2nd dim to first and 1 dim to third and so on

In [32]:
b=a.permute(1,0)
b

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [33]:
  #to add new dimension we use unsqueeze

In [35]:
print(a.shape)
b=a.unsqueeze(0)#at which pos we add dim
print(b.shape)

torch.Size([2, 3])
torch.Size([1, 2, 3])


In [36]:
#to remove dimension we use squeeze

In [42]:
print(a.shape)
b=a.squeeze(1)
b.shape

torch.Size([2, 3])


torch.Size([2, 3])

convert numpy array to tensor or vice versa


In [43]:
import numpy as np

In [45]:
a=torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [46]:
b=a.numpy()
b

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
c=torch.from_numpy(b)
c

tensor([[1, 2, 3],
        [4, 5, 6]])